FROM node:20-alpine

WORKDIR /app

# Installer les dépendances du système
RUN apk add --no-cache dumb-init

# Copier les fichiers de dépendances
COPY package.json package-lock.json ./

# Installer les dépendances (incluant les devDependencies)
RUN npm ci

# Copier le code source
COPY . .

EXPOSE 3000

ENV NEXT_TELEMETRY_DISABLED=1

ENTRYPOINT ["dumb-init", "--"]

CMD ["npm", "run", "dev"]
